[feat] ServiceBinding - CustomResource List 불러오기 기능 추가
tmax-cloud/hypercloud-api-server pull request #16
Opened 2022-08-10 07:03 UTC by 2smin

1. ServiceBinding 용 CustomResource List 불러오기 기능 추가
  - ClusterTemplate으로 등록된 CR 의 List 조회
  - K8s 기본 리소스 중 , Pod를 관리하는 Resource List 조회

2022-08-10 07:10 UTC, aldlfkahs requested changes

2022-08-10 07:10 UTC, aldlfkahs commented on main.go
> +func serveCustromResourceList(res http.ResponseWriter, req *http.Request) {
클라이언트의 method에 관계없이 실행되므로 다른 함수처럼 method를 특정지어서 받을 수 있도록 수정바랍니다.

2022-08-10 07:20 UTC, 2smin commented on main.go
> +func serveCustromResourceList(res http.ResponseWriter, req *http.Request) {
수정했습니다

2022-08-10 07:21 UTC, aldlfkahs approved these changes

2022-08-10 07:24 UTC, merged

2022-08-10 07:33 UTC, sisilia91 commented on util/caller/K8sApiCaller.go
> +	} else {
반드시 수정해야하는 부분은 아니지만 refactoring의 여지가 있어보여 코멘트 남깁니다.
if-else depth가 너무 깊어지면 코드가독성이 떨어지는 부분이 있으니, 
if err != nil { log; return nil }
// else 없이 이후 로직 작성
의 방식이 어떨지 건의드립니다.

2022-08-10 07:49 UTC, sisilia91 commented on util/caller/K8sApiCaller.go
> +					if err != nil {
해당 object의 kind 및 version은
objectKind.Object.GetObjectKind().GroupVersionKind().Version
objectKind.Object.GetObjectKind().GroupVersionKind().Kind
로 참조할 수 있기에 raw를 unmarshal함으로써 에러의 여지를 늘리는 것은 좋지않아보입니다.
링크된 패키지 참고바랍니다.
https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime#Object
https://pkg.go.dev/k8s.io/apimachinery@v0.24.3/pkg/runtime/schema#ObjectKind
https://pkg.go.dev/k8s.io/apimachinery@v0.24.3/pkg/runtime/schema#GroupVersionKind

2022-08-29 06:47 UTC, 2smin commented on util/caller/K8sApiCaller.go
> +	} else {
말씀해주신 의견 반영하여 로직 수정하였습니다

2022-08-29 06:48 UTC, 2smin commented on util/caller/K8sApiCaller.go
> +					if err != nil {
작성해주신 의견대로 수정 검토했으나, objectKind.Object 가 nil이라 참조가 불가능하여 
raw를 그대로 unmarshal하도록 유지하였습니다.
의견 감사합니다.